---
- src: https://github.com/jtyr/ansible-config_encoder_filters
  version: v1.21.0
  name: jtyr.config_encoder_filters

- src: https://github.com/vbotka/ansible-lib
  version: 2.2.0
  name: vbotka.ansible_lib
...
